2023-12-02 16:17:26,886 - test_dem.py[line:39] - ERROR: 断言失败，用例为：['老黄1号店', 'laohuang1hao', '老黄1号店的维度']。期望结果为:添加维度成功 - root
2023-12-02 16:17:30,419 - test_dem.py[line:39] - ERROR: 断言失败，用例为：['', 'laohuang1hao', '老黄1号店的维度']。期望结果为:添加维度失败 - root
2023-12-02 16:17:35,131 - test_dem.py[line:39] - ERROR: 断言失败，用例为：['老黄1号店', '', '老黄1号店的维度']。期望结果为:添加维度失败 - root
2023-12-02 16:17:48,053 - test_dem1.py[line:39] - ERROR: 断言失败，用例为：['老黄1号店', 'laohuang1hao', '老黄1号店的维度']。期望结果为:添加维度成功 - root
2023-12-02 16:17:51,656 - test_dem1.py[line:39] - ERROR: 断言失败，用例为：['', 'laohuang1hao', '老黄1号店的维度']。期望结果为:添加维度失败 - root
2023-12-02 16:17:56,406 - test_dem1.py[line:39] - ERROR: 断言失败，用例为：['老黄1号店', '', '老黄1号店的维度']。期望结果为:添加维度失败 - root
