2023-12-13 17:01:09,338 - i2share_log.py[line:34] - ERROR: 断言失败 - root
